/*
 * This file is generated by jOOQ.
 */
package models;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import models.tables.Comments;
import models.tables.Posts;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Oss extends SchemaImpl {

    private static final long serialVersionUID = -1300679563;

    /**
     * The reference instance of <code>oss</code>
     */
    public static final Oss OSS = new Oss();

    /**
     * The table <code>oss.COMMENTS</code>.
     */
    public final Comments COMMENTS = models.tables.Comments.COMMENTS;

    /**
     * The table <code>oss.POSTS</code>.
     */
    public final Posts POSTS = models.tables.Posts.POSTS;

    /**
     * No further instances allowed
     */
    private Oss() {
        super("oss", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Comments.COMMENTS,
            Posts.POSTS);
    }
}
