/*
 * This file is generated by jOOQ.
 */
package models;


import javax.annotation.Generated;

import models.tables.Comments;
import models.tables.Posts;


/**
 * Convenience access to all tables in oss
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>oss.COMMENTS</code>.
     */
    public static final Comments COMMENTS = models.tables.Comments.COMMENTS;

    /**
     * The table <code>oss.POSTS</code>.
     */
    public static final Posts POSTS = models.tables.Posts.POSTS;
}
