#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative 'calculator.rex'

class Calculator < Racc::Parser

module_eval(<<'...end calculator.y/module_eval...', 'calculator.y', 23)
  def parse(input)
    scan_str(input)
  end
...end calculator.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     5,     6,     7,     3,     8,     9,    10,    11,     2,
    12 ]

racc_action_check = [
     2,     2,     2,     2,     1,     3,     4,     5,     6,     0,
     7 ]

racc_action_pointer = [
     7,     4,    -3,     5,     4,     5,     6,     8,   nil,   nil,
   nil,   nil,   nil ]

racc_action_default = [
    -6,    -6,    -1,    -6,    -6,    -6,    -6,    -6,    13,    -2,
    -3,    -4,    -5 ]

racc_goto_table = [
     1 ]

racc_goto_check = [
     1 ]

racc_goto_pointer = [
   nil,     0 ]

racc_goto_default = [
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 8, :_reduce_none,
  3, 8, :_reduce_2,
  3, 8, :_reduce_3,
  3, 8, :_reduce_4,
  3, 8, :_reduce_5 ]

racc_reduce_n = 6

racc_shift_n = 13

racc_token_table = {
  false => 0,
  :error => 1,
  :DIGIT => 2,
  :ADD => 3,
  :SUBSTRACT => 4,
  :MULTIPLY => 5,
  :DIVIDE => 6 }

racc_nt_base = 7

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DIGIT",
  "ADD",
  "SUBSTRACT",
  "MULTIPLY",
  "DIVIDE",
  "$start",
  "expression" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'calculator.y', 12)
  def _reduce_2(val, _values, result)
     return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'calculator.y', 13)
  def _reduce_3(val, _values, result)
     return val[0] - val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'calculator.y', 14)
  def _reduce_4(val, _values, result)
     return val[0] * val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'calculator.y', 15)
  def _reduce_5(val, _values, result)
     return val[0] / val[2] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Calculator
